// Hardcoded tour data to be migrated to database
export const TOURS_TO_MIGRATE = [
    {
        name: "Chitwan tour",
        slug: "chitwan-tour",
        location: "Chitwan, Nepal",
        description: "Explore the wildlife and natural beauty of Chitwan",
        longDescription: "Discover the rich biodiversity of Chitwan National Park, home to rare one-horned rhinoceros and Bengal tigers.",
        price: 899,
        duration: "5 days",
        maxGroupSize: 12,
        difficulty: 1,
        rating: 4.7,
        latitude: 27.5291,
        longitude: 84.3542,
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Jungle safari in Chitwan National Park",
            "Canoe ride on Rapti River",
            "Visit elephant breeding center",
            "Bird watching experience",
        ],
        includes: ["Accommodation", "Meals", "Park entrance fees", "Guided safari"],
        excludes: ["International flights", "Personal expenses", "Travel insurance"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Kathmandu tour",
        slug: "kathmandu-tour",
        location: "Kathmandu, Nepal",
        description: "Discover the ancient temples and culture of Kathmandu",
        longDescription: "Immerse in the vibrant capital city with its UNESCO World Heritage sites and rich cultural heritage.",
        price: 699,
        duration: "4 days",
        maxGroupSize: 15,
        difficulty: 1,
        rating: 4.9,
        latitude: 27.7172,
        longitude: 85.3240,
        coverImage: "https://images.unsplash.com/photo-1548013146-72d440642117?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Visit Swayambhunath Stupa",
            "Explore Durbar Square",
            "Tour Pashupatinath Temple",
            "Experience local markets",
        ],
        includes: ["Accommodation", "Breakfast", "Temple entrance fees", "Guide"],
        excludes: ["Lunch and dinner", "International flights", "Personal expenses"],
        isActive: true,
        isFeatured: true,
    },
    {
        name: "Pokhara tour",
        slug: "pokhara-tour",
        location: "Pokhara, Nepal",
        description: "Experience the lakeside beauty and mountain views of Pokhara",
        longDescription: "Relax by Phewa Lake with stunning Annapurna mountain range as your backdrop in Nepal's adventure capital.",
        price: 799,
        duration: "6 days",
        maxGroupSize: 12,
        difficulty: 2,
        rating: 4.8,
        latitude: 28.2096,
        longitude: 83.9856,
        coverImage: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Boat ride on Phewa Lake",
            "Sunrise at Sarangkot",
            "Visit Davis Falls",
            "Paragliding experience",
        ],
        includes: ["Accommodation", "Breakfast", "Boat ride", "Sightseeing"],
        excludes: ["Paragliding cost", "Lunch and dinner", "Personal expenses"],
        isActive: true,
        isFeatured: true,
    },
    {
        name: "Lumbini tour",
        slug: "lumbini-tour",
        location: "Lumbini, Nepal",
        description: "Visit the birthplace of Lord Buddha",
        longDescription: "Explore the sacred pilgrimage site where Buddha was born, featuring ancient monasteries and peaceful gardens.",
        price: 599,
        duration: "3 days",
        maxGroupSize: 15,
        difficulty: 1,
        rating: 4.9,
        latitude: 27.4833,
        longitude: 83.2833,
        coverImage: "https://images.unsplash.com/photo-1516214104703-3e691de8e4ad?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Maya Devi Temple visit",
            "Meditation in sacred gardens",
            "Tour international monasteries",
            "Ancient Ashoka Pillar",
        ],
        includes: ["Accommodation", "Meals", "Temple entrance", "Guide"],
        excludes: ["International flights", "Personal expenses", "Donations"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Rara tour",
        slug: "rara-tour",
        location: "Rara, Nepal",
        description: "Trek to Nepal's largest and deepest lake",
        longDescription: "Journey to the pristine Rara Lake, Nepal's hidden gem surrounded by pine forests and snow-capped peaks.",
        price: 1299,
        duration: "10 days",
        maxGroupSize: 10,
        difficulty: 4,
        rating: 4.9,
        latitude: 29.5300,
        longitude: 82.0800,
        coverImage: "https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Camp by Rara Lake shores",
            "Trek through Rara National Park",
            "Wildlife spotting",
            "Pristine mountain scenery",
        ],
        includes: ["Accommodation", "All meals", "Park fees", "Porter service"],
        excludes: ["International flights", "Personal gear", "Tips"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Illam tour",
        slug: "illam-tour",
        location: "Illam, Nepal",
        description: "Explore the tea gardens and scenic hills of Illam",
        longDescription: "Discover the lush green tea estates and breathtaking sunrise views from the eastern hills of Nepal.",
        price: 699,
        duration: "5 days",
        maxGroupSize: 12,
        difficulty: 2,
        rating: 4.7,
        latitude: 26.9094,
        longitude: 87.9283,
        coverImage: "https://images.unsplash.com/photo-1531065208531-4036c0dba3f5?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Visit tea plantation estates",
            "Sunrise at Kanyam",
            "Local tea tasting experience",
            "Explore Antu Danda viewpoint",
        ],
        includes: ["Accommodation", "Meals", "Tea factory tour", "Guide"],
        excludes: ["Transportation to Illam", "Personal expenses"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Rara Lake tour",
        slug: "rara-lake-tour",
        location: "Rara Lake, Nepal",
        description: "Experience the crystal clear waters of Rara Lake",
        longDescription: "Visit Nepal's largest lake, a hidden paradise in the remote northwest with stunning alpine scenery.",
        price: 1199,
        duration: "8 days",
        maxGroupSize: 10,
        difficulty: 3,
        rating: 4.8,
        latitude: 29.5400,
        longitude: 82.0700,
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Crystal clear lake views",
            "Forest trekking experience",
            "Local Thakuri culture",
            "Photography opportunities",
        ],
        includes: ["Accommodation", "All meals", "National park fees", "Guide"],
        excludes: ["Flight to/from Talcha", "Personal expenses", "Tips"],
        isActive: true,
        isFeatured: false,
    },
];
