// Hardcoded trek data to be migrated to database (truncated for brevity - showing structure)
export const TREKS_TO_MIGRATE = [
    {
        name: "Annapurna Base Camp Trek",
        slug: "annapurna-base-camp",
        location: "Annapurna, Nepal",
        description: "Trek to the sanctuary of Annapurna surrounded by towering peaks",
        longDescription: "Journey through diverse landscapes from lush rhododendron forests to high-altitude alpine meadows, culminating at Annapurna Base Camp at 4,130m with 360-degree mountain views.",
        price: 1299,
        duration: "12 days",
        maxGroupSize: 12,
        difficulty: 3,
        rating: 4.9,
        altitude: "4,130m",
        latitude: 28.5300,
        longitude: 83.8800,
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "360-degree mountain panorama at base camp",
            "Trek through traditional Gurung villages",
            "Rhododendron forests and alpine meadows",
            "Close-up views of Annapurna I (8,091m)",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["Accommodation", "All meals", "Permits", "Guide and porter"],
        excludes: ["International flights", "Personal gear", "Travel insurance"],
        isActive: true,
        isFeatured: true,
    },
    {
        name: "Everest Base Camp Trek",
        slug: "everest-base-camp",
        location: "Everest, Nepal",
        description: "Stand at the foot of the world's highest mountain",
        longDescription: "Follow in the footsteps of legendary mountaineers on this iconic trek to Everest Base Camp. Experience Sherpa culture, visit ancient monasteries, and witness the majesty of Mount Everest up close.",
        price: 1699,
        duration: "14 days",
        maxGroupSize: 10,
        difficulty: 4,
        rating: 4.9,
        altitude: "5,364m",
        latitude: 28.0026,
        longitude: 86.8528,
        coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Reach Everest Base Camp at 5,364m",
            "Summit Kala Patthar for panoramic Everest views",
            "Visit Tengboche Monastery",
            "Sherpa villages and mountain culture",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["Accommodation", "All meals", "Permits", "Guide and porter"],
        excludes: ["International flights", "Personal gear", "Travel insurance", "Tips"],
        isActive: true,
        isFeatured: true,
    },
    {
        name: "Gokyo Trek",
        slug: "gokyo",
        location: "Gokyo, Nepal",
        description: "Turquoise alpine lakes and panoramic mountain views",
        longDescription: "Trek to the stunning Gokyo Lakes, sacred turquoise waters set amid towering Himalayas. Summit Gokyo Ri for one of the best viewpoints in the Everest region.",
        price: 1399,
        duration: "12 days",
        maxGroupSize: 12,
        difficulty: 3,
        rating: 4.9,
        altitude: "5,357m",
        latitude: 27.9600,
        longitude: 86.6900,
        coverImage: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Six sacred turquoise Gokyo Lakes",
            "Summit Gokyo Ri (5,357m)",
            "Views of Everest, Lhotse, Makalu, Cho Oyu",
            "Walk on Ngozumpa Glacier",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["Accommodation", "All meals", "Permits", "Guide"],
        excludes: ["Flights", "Personal expenses", "Tips"],
        isActive: true,
        isFeatured: true,
    },
    {
        name: "Manaslu Trek",
        slug: "manaslu",
        location: "Manaslu, Nepal",
        description: "Remote trek around the eighth highest mountain",
        longDescription: "Circle the majestic Mount Manaslu on this stunning trek. Experience authentic Himalayan culture in remote villages and witness breathtaking mountain scenery.",
        price: 1499,
        duration: "14 days",
        maxGroupSize: 10,
        difficulty: 4,
        rating: 4.8,
        altitude: "5,106m",
        latitude: 28.5500,
        longitude: 84.5600,
        coverImage: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Trek around Mount Manaslu (8,163m)",
            "Remote Buddhist monasteries",
            "Authentic mountain village culture",
            "Spectacular Himalayan scenery",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["Accommodation", "All meals", "Permits", "Guide"],
        excludes: ["Flights", "Gear", "Tips"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Manaslu Circuit Trek",
        slug: "manaslu-circuit",
        location: "Manaslu, Nepal",
        description: "Complete circuit around Mount Manaslu",
        longDescription: "Experience the full Manaslu Circuit, crossing the challenging Larkya La Pass. This remote trek offers incredible mountain views and authentic cultural experiences.",
        price: 1599,
        duration: "16 days",
        maxGroupSize: 10,
        difficulty: 4,
        rating: 4.9,
        altitude: "5,106m",
        latitude: 28.5500,
        longitude: 84.5600,
        coverImage: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Cross Larkya La Pass at 5,106m",
            "Complete circuit around Manaslu",
            "Remote mountain villages",
            "Tibetan Buddhist culture",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["All meals", "Accommodation", "Permits", "Guide"],
        excludes: ["Flights", "Gear", "Tips"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Langtang Valley Trek",
        slug: "langtang-valley",
        location: "Langtang, Nepal",
        description: "Pristine valley trek close to Kathmandu",
        longDescription: "Explore the stunning Langtang Valley, often called the 'Valley of Glaciers.' This less-crowded trek offers incredible mountain views, Tamang culture, and beautiful forests.",
        price: 899,
        duration: "8 days",
        maxGroupSize: 12,
        difficulty: 2,
        rating: 4.8,
        altitude: "3,870m",
        latitude: 28.2096,
        longitude: 85.5500,
        coverImage: "https://images.unsplash.com/photo-1589182373726-e4f658ab50b0?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Less crowded alternative to popular treks",
            "Tamang cultural immersion",
            "Kyanjin Gompa monastery visit",
            "Glacier views and cheese factory tour",
        ],
        bestSeason: ["Spring", "Autumn", "Winter"],
        includes: ["Accommodation", "Meals", "Permits", "Guide"],
        excludes: ["Transportation", "Tips"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Gosaikunda Trek",
        slug: "gosaikunda",
        location: "Langtang, Nepal",
        description: "Sacred alpine lakes pilgrimage trek",
        longDescription: "Trek to the sacred Gosaikunda Lakes, a pilgrimage site with stunning alpine scenery. Experience the spiritual significance of these holy waters while enjoying spectacular mountain views.",
        price: 799,
        duration: "7 days",
        maxGroupSize: 12,
        difficulty: 2,
        rating: 4.7,
        altitude: "4,380m",
        latitude: 28.0800,
        longitude: 85.4100,
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Sacred Gosaikunda Lake pilgrimage",
            "Stunning alpine lake scenery",
            "Langtang Himalayan views",
            "Rich spiritual and cultural experience",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["Accommodation", "Meals", "Guide"],
        excludes: ["Transportation", "Gear"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Kanchenjunga Trek",
        slug: "kanchenjunga",
        location: "Kanchenjunga, Nepal",
        description: "Trek to the base of the world's third highest peak",
        longDescription: "Journey to the remote Kanchenjunga region, home to the world's third highest mountain. Experience pristine wilderness, diverse ecosystems, and authentic local culture.",
        price: 1899,
        duration: "20 days",
        maxGroupSize: 8,
        difficulty: 5,
        rating: 4.9,
        altitude: "5,143m",
        latitude: 27.7025,
        longitude: 88.1475,
        coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Base camp of third highest peak",
            "Remote and pristine wilderness",
            "Diverse flora and fauna",
            "Authentic Limbu and Sherpa culture",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["All meals", "Accommodation", "Permits", "Guide and porter"],
        excludes: ["Flights", "Gear", "Insurance"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Makalu Barun Trek",
        slug: "makalu-barun",
        location: "Makalu, Nepal",
        description: "Explore the remote Makalu region and national park",
        longDescription: "Trek through the pristine Makalu Barun National Park to the base of Mount Makalu, the fifth highest mountain in the world. Experience incredible biodiversity and remote mountain culture.",
        price: 1799,
        duration: "18 days",
        maxGroupSize: 8,
        difficulty: 5,
        rating: 4.8,
        altitude: "4,870m",
        latitude: 27.8894,
        longitude: 87.0889,
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Base camp of Mount Makalu (8,485m)",
            "Pristine national park biodiversity",
            "Remote Rai and Sherpa villages",
            "Spectacular mountain scenery",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["Meals", "Accommodation", "Permits", "Guide"],
        excludes: ["Flights", "Gear", "Tips"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Ama Yangri Trek",
        slug: "ama-yangri",
        location: "Helambu, Nepal",
        description: "Short trek with panoramic Himalayan views",
        longDescription: "A short but rewarding trek to Ama Yangri peak, offering spectacular panoramic views of the Himalayas including Langtang, Ganesh Himal, and Jugal ranges. Perfect for those with limited time.",
        price: 599,
        duration: "5 days",
        maxGroupSize: 12,
        difficulty: 2,
        rating: 4.6,
        altitude: "3,771m",
        latitude: 28.0500,
        longitude: 85.5500,
        coverImage: "https://images.unsplash.com/photo-1589182373726-e4f658ab50b0?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Panoramic Himalayan sunrise views",
            "Close to Kathmandu valley",
            "Sherpa village cultural experience",
            "Perfect for limited time schedules",
        ],
        bestSeason: ["Spring", "Autumn", "Winter"],
        includes: ["Meals", "Accommodation", "Guide"],
        excludes: ["Transportation", "Tips"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Dolpo Trek",
        slug: "dolpo",
        location: "Dolpo, Nepal",
        description: "Journey to the remote Tibetan plateau region",
        longDescription: "Trek through the mystical Dolpo region, one of Nepal's most remote areas. Experience ancient Tibetan Buddhist culture, dramatic landscapes, and the famous Shey Phoksundo Lake.",
        price: 2299,
        duration: "22 days",
        maxGroupSize: 8,
        difficulty: 5,
        rating: 4.9,
        altitude: "5,360m",
        latitude: 29.1500,
        longitude: 82.8500,
        coverImage: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Ancient Tibetan Buddhist culture",
            "Shey Phoksundo Lake crystal waters",
            "Remote trans-Himalayan landscapes",
            "Unique Bon Po culture",
        ],
        bestSeason: ["Spring", "Summer", "Autumn"],
        includes: ["All meals", "Accommodation", "Permits", "Guide and porter"],
        excludes: ["Flights", "Gear", "Insurance"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Upper Mustang Trek",
        slug: "upper-mustang",
        location: "Mustang, Nepal",
        description: "Forbidden kingdom behind the Himalayas",
        longDescription: "Journey to the ancient kingdom of Lo, Upper Mustang. Experience the preserved Tibetan Buddhist culture, dramatic desert landscapes, and the walled city of Lo Manthang.",
        price: 2199,
        duration: "16 days",
        maxGroupSize: 8,
        difficulty: 3,
        rating: 4.9,
        altitude: "3,840m",
        latitude: 29.1800,
        longitude: 83.9500,
        coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Walled city of Lo Manthang",
            "Ancient Tibetan Buddhist monasteries",
            "Desert-like trans-Himalayan landscape",
            "Preserved medieval culture",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["Meals", "Accommodation", "Special permits", "Guide"],
        excludes: ["Flights", "Gear", "Tips"],
        isActive: true,
        isFeatured: true,
    },
    {
        name: "Dhorpatan Trek",
        slug: "dhorpatan",
        location: "Dhorpatan, Nepal",
        description: "Wildlife and hunting reserve adventure",
        longDescription: "Trek through Nepal's only hunting reserve, home to diverse wildlife including blue sheep and snow leopard. Experience remote valleys, high passes, and authentic mountain culture.",
        price: 1299,
        duration: "12 days",
        maxGroupSize: 10,
        difficulty: 3,
        rating: 4.7,
        altitude: "4,500m",
        latitude: 28.5500,
        longitude: 83.0500,
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Nepal's only hunting reserve",
            "Blue sheep and wildlife spotting",
            "Remote Magar villages",
            "High mountain passes",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["Meals", "Accommodation", "Permits", "Guide"],
        excludes: ["Flights", "Gear", "Tips"],
        isActive: true,
        isFeatured: false,
    },
    {
        name: "Shey Phoksundo Trek",
        slug: "shey-phoksundo",
        location: "Dolpo, Nepal",
        description: "Deepest lake in Nepal and pristine wilderness",
        longDescription: "Trek to the stunning Shey Phoksundo Lake, Nepal's deepest lake with crystal turquoise waters. Experience the pristine Dolpo-pa culture and remote Himalayan wilderness.",
        price: 1699,
        duration: "14 days",
        maxGroupSize: 10,
        difficulty: 4,
        rating: 4.8,
        altitude: "3,612m",
        latitude: 29.2000,
        longitude: 82.9500,
        coverImage: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop",
        images: [],
        highlights: [
            "Nepal's deepest and most beautiful lake",
            "Crystal turquoise alpine waters",
            "Shey Gompa ancient monastery",
            "Remote Dolpo-pa culture",
        ],
        bestSeason: ["Spring", "Autumn"],
        includes: ["Meals", "Accommodation", "Permits", "Guide"],
        excludes: ["Flights", "Gear", "Insurance"],
        isActive: true,
        isFeatured: false,
    },
];
